### ISSUE TITLE
Failure building container - NPM run build don't work

### ISSUE THREAD

**Issue by djogopatrao** [OHDSI/Broadsea-WebTools#10]
Steps to reproduce:

$ git clone a2d7d1ec85077aa4ed008f83465da6313eea0122

$ docker-compose build --no-cache

`
Step 15/22 : RUN npm run build
 ---> Running in ea4b1e41bd3d
npm does not support Node.js v10.24.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
ERROR: Service 'broadsea-webtools' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
`

**Comment by djogopatrao** [comment]
proposed solution is to specify npm version

**Comment by leeevans** [comment]
Thanks for reporting the issue. 
Updated the Dockerfile to install a compatible npm version in commit: 64df158
