### ISSUE TITLE
Docker Build fails: ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js'

### ISSUE THREAD

**Issue by ssaranathan** [OHDSI/Broadsea-WebTools#7]
> atlas@2.8.0 build:dev /usr/local/tomcat/webapps/atlas
> node build/optimize.js && npm run compress

[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
{ Error: Error: ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js'
In module tree:
    main
      pages/Router

    at Object.openSync (fs.js:443:3)

    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28332:19
    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3059:39
    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2999:25
    at Function.prim.nextTick (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28083:9)
    at Object.errback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2998:26)
    at Object.callback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2984:23)
    at Object.then (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3038:23)
    at build (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28289:12)
    at runBuild (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:30302:17)
    at Object.execCb (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:1946:33)
  originalError:
   { Error: ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js'
       at Object.openSync (fs.js:443:3)
       at Object.readFileSync (fs.js:343:35)
       at Object.readFile (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3658:27)
       at Object.readFileAsync (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3672:32)
       at Function.require._cacheReadAsync (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28102:25)
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:27671:48
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3041:37
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2989:25
       at Function.prim.nextTick (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28083:9)
       at Object.callback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2988:26)
     errno: -2,
     syscall: 'open',
     code: 'ENOENT',
     path: '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js',
     fileName: '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js',
     moduleTree: [ 'pages/Router', 'main' ] } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atlas@2.8.0 build:dev: `node build/optimize.js && npm run compress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atlas@2.8.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-13T19_01_39_777Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atlas@2.8.0 build: `npm run prep && npm run build:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atlas@2.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-13T19_01_39_802Z-debug.log

**Comment by ssaranathan** [comment]
Following up with OHDSI Forum collaborators in this thread:
https://forums.ohdsi.org/t/npn-build-on-latest-atlas-code-gives-enoent-no-such-file-or-directory-open-usr-local-tomcat-webapps-atlas-node-modules-qs-dist-qs-js/12946/3
